### ISSUE TITLE
Why is RestAdapter Singleton and not a dependency ?

### ISSUE THREAD

**Issue by pdegand** [fr4nk1/retro-dagger-example#1]
Hello,

Great article about MVP + Dagger 2 + Retrofit. Helped me a lot.

I just have a question about the RestAdapter. In the current version of the code, the RestAdapter is a self implemented Singleton (with some flaws in the impl tbh) and not a dependency provided by Dagger ?

Why did you choose to do like this and did not put this dependency in the InteractorModule ?
The RestAdapter could be injected in the constructor of the FindItemsInteractorImpl and you will have the behavious properly implemented with Dagger2.
Or maybe i'm missing a point of Dagger and/or Retrofit that prevents you to do such things.

Thank you

**Comment by fr4nk1** [comment]
Hello Pierre,

I'm glad that my code helps you.

Indeed your aproach is correct. RestAdapter must be in the InteractorModule
because many interactors will use RestAdapter.

If I have a free moment this week, I will update the code.

Thanks for your time and to report me this.

Best regards.
-Fran.

2015-04-27 8:49 GMT+02:00 Pierre Degand notifications@github.com:

**Comment by vwmattr** [comment]
I added [PR 2](https://github.com/fr4nk1/retro-dagger-example/pull/2) to inject the RestAdapter in the InteractorModule.  Took it as an opportunity to try and test my understanding of what I learned from the blog post and this repo.  Please let me know if that is what you had in mind @fr4nk1 or if there's something you'd change to improve that.

**Comment by fr4nk1** [comment]
I like your approach @vwmattr . I am thinking in reuse the method in other interactors and it's good.
@pdegand I going to close this issue, this approach resolve the problem ;)
